log:
  disable_sentry: true
  level: debug

db:
  url: db_url

listener:
  addr: :8000

cop:
  disabled: true
  endpoint: "http://..."
  upstream: "http://..."
  service_name: keyserver-svc
  service_port: 80

wallets:
  disable_confirm: true

notificator:
  disabled: true
  client_router: http://localhost:8000
  endpoint: http://traefik/integrations/notifications

tfa_params:
  digits: 6